In [12]:
import numpy as np
import seaborn as sns
import pandas as pd
import sklearn.datasets

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [13]:
class KNN():
    
    def __init(self):
        self.K = None
        self.X_train = None
        self.y_train = None
        self.vizinhos_index = None
        
    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train
        
    def predict(self, X, K=1):
        self.K = K
        classes = np.unique(self.y_train)
        y_pred = []
        dist_total = []
        self.vizinhos_index = []

        for xi in X:
            euclidistancias = -2 * xi @ self.X_train.T + (xi**2).sum() + (self.X_train**2).sum(axis=1)
            
            
            knn_index = np.argsort(euclidistancias)[0:K]
            self.vizinhos_index.append(knn_index)
            contagem = []
            dist_total = []
            
            for classe in classes:
                contagem.append((self.y_train[knn_index]==classe).sum())
                dist_classe = np.sum(euclidistancias[knn_index][self.y_train[knn_index]==classe])
                dist_total.append(dist_classe)
                
            contagem = np.array(contagem)
            
            #criar lista de classes empatadas
            indice_classes_empatadas = []
            for i in range(len(contagem)):
                if contagem[i] == max(contagem):
                    indice_classes_empatadas.append(i)
            
            # Popular y_pred com as duas regras de decisão: 
                # Se não empate: classe com maior votação
                # Se empate: classe com menor distância entre as classes empatadas
            
            dist_total = np.array(dist_total)

            if len(indice_classes_empatadas) == 1:
                pred_index = np.argmax(contagem)
                y_pred.append(classes[pred_index])
                
                
    
            else:
                # menor valor das distancias totais que estão com a mesma quantidade de votos
                menor_valor = np.min(dist_total[indice_classes_empatadas])
                
                # indice da menor distancia contando todas as distâncias
                indice_menor_dist = np.where(dist_total == menor_valor)[0][0]
                
                # Predição pra essa instância = Classe que tem a menor distancia
                y_pred.append(classes[indice_menor_dist])
            

            
        return np.array(y_pred)

In [14]:
from sklearn.datasets import load_breast_cancer
X, y = load_breast_cancer(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=13)

In [16]:
knn.fit(X_train, y_train)

In [24]:
knn.X_train

array([[1.221e+01, 1.409e+01, 7.878e+01, ..., 9.140e-02, 2.677e-01,
        8.824e-02],
       [9.742e+00, 1.912e+01, 6.193e+01, ..., 4.589e-02, 3.196e-01,
        8.009e-02],
       [1.057e+01, 1.832e+01, 6.682e+01, ..., 2.222e-02, 2.699e-01,
        6.736e-02],
       ...,
       [1.231e+01, 1.652e+01, 7.919e+01, ..., 8.660e-02, 2.618e-01,
        7.609e-02],
       [9.904e+00, 1.806e+01, 6.460e+01, ..., 9.910e-02, 2.614e-01,
        1.162e-01],
       [1.005e+01, 1.753e+01, 6.441e+01, ..., 6.499e-02, 2.894e-01,
        7.664e-02]])

In [17]:
y_pred = knn.predict(X_test, 4)

In [10]:
knn.vizinhos_index

[array([381, 419, 107, 355], dtype=int64),
 array([ 58, 352,  14, 153], dtype=int64),
 array([ 99,  36, 132, 151], dtype=int64),
 array([282, 313,  94, 381], dtype=int64),
 array([330, 347, 152, 151], dtype=int64),
 array([159, 337, 110, 138], dtype=int64),
 array([ 42, 107, 419, 380], dtype=int64),
 array([400, 399, 176, 265], dtype=int64),
 array([281, 339, 133,  60], dtype=int64),
 array([101, 361,  41, 229], dtype=int64),
 array([130, 406, 391, 232], dtype=int64),
 array([397, 233,  27, 192], dtype=int64),
 array([378, 383,   0, 393], dtype=int64),
 array([158, 403, 410, 111], dtype=int64),
 array([194, 395, 353, 189], dtype=int64),
 array([314, 160, 125,  38], dtype=int64),
 array([163, 417, 186, 335], dtype=int64),
 array([329, 314, 160, 352], dtype=int64),
 array([372,  60, 339, 119], dtype=int64),
 array([111, 124, 316, 158], dtype=int64),
 array([ 16,  38, 272,  34], dtype=int64),
 array([282, 313,  94, 381], dtype=int64),
 array([128, 273,  45, 209], dtype=int64),
 array([269

In [20]:
XX.shape

(569, 30)

In [11]:
accuracy_score(y_pred, y_test)

0.916083916083916

In [ ]:
# Modelo com código procedural

K = 4
classes = np.unique(y_train)
y_pred = []
vizinhos_index = []
        
for xi in X_test:
    euclidistancias = -2 * xi @ X_train.T + (xi**2).sum() + (X_train**2).sum(axis=1)
            
    knn_index = np.argsort(euclidistancias)[0:K]
    vizinhos_index.append(knn_index)
    
    contagem = []
    dist_total = []
    
    for classe in classes:
        contagem.append((y_train[knn_index]==classe).sum())
        dist_classe = np.sum(euclidistancias[knn_index][y_train[knn_index]==classe])
        dist_total.append(dist_classe)
    
    contagem = np.array(contagem)
    
    #criar lista de classes empatadas
    indice_classes_empatadas = []
    for i in range(len(contagem)):
        if contagem[i] == max(contagem):
            indice_classes_empatadas.append(i)
      
    # Popular y_pred com as duas regras de decisão: 
        # Se não empate: classe com maior votação
        # Se empate: classe com menor distância entre as classes empatadas
    
    dist_total = np.array(dist_total)
    
    if len(indice_classes_empatadas) == 1:
        pred_index = np.argmax(contagem)
        y_pred.append(classes[pred_index])
    
    else:
        # menor valor das distancias totais que estão com a mesma quantidade de votos
        menor_valor = np.min(dist_total[indice_classes_empatadas])

        # indice da menor distancia contando todas as distâncias
        indice_menor_dist = np.where(dist_total == menor_valor)[0][0]

        # Classe que tem a menor distancia
        y_pred.append(classes[indice_menor_dist])
        
        #bloco de teste
        print("----------------------------Check de sanidade para instâncias com empate-----------------------------")

        print("contagem: ")
        print(contagem)
        print("dist_total: ")
        print(dist_total)
        print("menor_valor: ")
        print(menor_valor)
        print("indice_menor_dist: ")
        print(indice_menor_dist)
        
        
            
y_pred = np.array(y_pred)

In [ ]:
(y_train[knn_index]==classe)

In [ ]:
((y_train[knn_index]==classe).sum())

In [ ]:
vizinhos_index

In [ ]:
euclidistancias

In [ ]:
knn_index

In [ ]:
dist_total

In [ ]:
accuracy_score(y_pred, y_test)

In [ ]:
# Modelo com código procedural

K = 4
classes = np.unique(y_train)
y_pred = []
vizinhos_index = []
        
for xi in X_test:
    
    euclidistancias = -2 * xi @ X_train.T + (xi**2).sum() + (X_train**2).sum(axis=1)        
    knn_index = np.argsort(euclidistancias)[0:K]
    vizinhos_index.append(knn_index)
    
    contagem = []
    dist_total = []
    
    for classe in classes:
        contagem.append((y_train[knn_index]==classe).sum())
        dist_classe = np.sum(euclidistancias[knn_index][y_train[knn_index]==classe])
        dist_total.append(dist_classe)
    
    contagem = np.array(contagem)
    indice_classes_empatadas = []
    for i in range(len(contagem)):
        if contagem[i] == max(contagem):
            indice_classes_empatadas.append(i)
          
    dist_total = np.array(dist_total)
    
    if len(indice_classes_empatadas) == 1:
        pred_index = np.argmax(contagem)
        y_pred.append(classes[pred_index])
    
    else:
        menor_valor = np.min(dist_total[indice_classes_empatadas])
        indice_menor_dist = np.where(dist_total == menor_valor)[0][0]
        y_pred.append(classes[indice_menor_dist])
                        
y_pred = np.array(y_pred)

In [ ]:
K = 4
classes = np.unique(y_train)
y_pred = []
vizinhos_index = []

In [ ]:
classes